/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package escapefromuniversity;


import javafx.application.Application;

/** Main application entry-point. */

public final class App {
    private App() { }

    public static void main(final String[] args) {
        Application.launch(MainView.class, args);
    }
}
